### ISSUE TITLE
Add step indicator to standards index page.

### ISSUE THREAD

**Issue by evoeges** [GSA-TTS/federal-website-standards#234]
### Describe your suggestion for this website.

Tasks:

- [x] add step indicator to standards index page under 'Standards' heading. All steps should be in the 'current segment' color (#005ea2)
- [x] add H2 sections for each stage of the standards (research, draft, pending, required)
- [x] add explainer text for each section
- [x] display cards under corresponding section.

note: required section will currently have no cards

mockup: ![Image](https://github.com/user-attachments/assets/621a9de1-ed31-48e0-a65e-fdbf5cb533f1)

**Comment by caleywoods** [comment]
@evoeges @michelle-rago For the explainer text under "Required standards" it says they'll be added incrementally which is true, standards will move incrementally through each status and from pending to required but should there be information either under "Required" or "Pending" that explains the plan to have the current pending standards become required one year after launch so that the individual pending standard pages are not the only place that information is presented. I feel like having something on the overview page helps give more context in one less click.

**Comment by michelle-rago** [comment]
> @evoeges @michelle-rago For the explainer text under "Required standards" it says they'll be added incrementally which is true, standards will move incrementally through each status and from pending to required but should there be information either under "Required" or "Pending" that explains the plan to have the current pending standards become required one year after launch so that the individual pending standard pages are not the only place that information is presented. I feel like having something on the overview page helps give more context in one less click.

The amount of time a standard will be pending won't always be one year. At some point we'll need to have timeline buckets (6 months, one year, 18 months...).  That being said, how about this for the required text:

"There are no required standards yet. Pending standards will be required after a specified period of time."

**Comment by evoeges** [comment]
That was just some filler text I added, thanks for the fix!
